backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "reusable-content"
    label: "Reusable"
    create: false
    files:
      - file: "src/components/Sponsors/index.md"
        name: "sponsors"
        label: "Sponsors"
        create: true
        widget: "object"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "sponsors",
            }
          - { label: "Section Title", name: "title", widget: "string" }
          - label: "Featured Sponsors"
            name: "featuredSponsors"
            widget: "list"
            fields:
            - { label: "Sponsor Name", name: "title", widget: "string" }
            - { label: "Sponsor Image", name: "imgLink", widget: "image" }
        - file: "src/components/SocialMedia/index.md"
        name: "Social Media"
        label: "socialMedia"
        create: true
        widget: "list"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "sponsors",
            }
          - { label: "Facebook", name: "facebookLink", widget: "string" }
          - { label: "Instagram", name: "instagramLink", widget: "string" }
          - { label: "Email", name: "emailLink", widget: "string" }
      - file: "src/components/RecentEvents/index.md"
        name: "Recent Events"
        label: "Recent Events"
        create: true
        widget: "object"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "recent-events",
            }
          - { label: "Section Title", name: "title", widget: "string" }
          - label: "Featured Events"
            name: "featuredEvents"
            widget: "list"
            fields:
              - { label: "Event Name", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "date" }
              - { label: "Event Link", name: "link", widget: "string" }
      - file: "src/components/BeyondSwe/index.md"
        name: "BeyondSWE"
        label: "Beyond SWE"
        create: true
        widget: "object"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "beyondSwe",
            }
          - { label: "Section Title", name: "title", widget: "string" }
          - { label: "description", name: "description", widget: "string" }
          - label: "Featured Links"
            name: "featuredLinks"
            widget: "list"
            fields:
              - { label: "Link Title", name: "linkTitle", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
  - name: "pages"
    label: "Pages"
    create: false
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: "Main Section Heading",
              name: sectionTitle,
              widget: string,
            }
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: "Main Section Heading",
              name: sectionTitle,
              widget: string,
            }
          - {
              label: "Main Section Description",
              name: sectionDescription,
              widget: string,
            }
      - file: "src/pages/calendar/index.md"
        label: "Calendar Page"
        name: "calendar"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "calendar-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: "Calendar Link Title",
              name: "calLinkTitle",
              widget: "string",
            }
          - { label: "Calendar URL", name: "calURL", widget: "string" }
      - file: "src/pages/envision/index.md"
        label: "Envision Page"
        name: "envision"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "envision-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
      - file: "src/pages/social/index.md"
        label: "Social Page"
        name: "social"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "social-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: "Events Section Title",
              name: sectionTitle,
              widget: string,
            }
          - {
              label: "Events Section Description",
              name: sectionDescription,
              widget: string,
            }
          - label: "Upcoming Events"
            name: "socialEvents"
            widget: "list"
            create: true
            fields:
              - {
                  label: "Event Title",
                  name: "socialEventTitle",
                  widget: "string",
                }
              - {
                  label: "Event Description ",
                  name: "socialEventDescription",
                  widget: "string",
                }
              - { label: "Photo", name: "socialEventImage", widget: "image" }
          - {
              label: "Calendar Link Title",
              name: "calLinkTitle",
              widget: "string",
            }
          - { label: "Calendar URL", name: "calURL", widget: "string" }
      - file: "src/pages/professional/index.md"
        label: "Professional Page"
        name: "professional"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "professional-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: "Events Section Title",
              name: sectionTitle,
              widget: string,
            }
          - {
              label: "Events Section Description",
              name: sectionDescription,
              widget: string,
            }
          - label: "Upcoming Events"
            name: "profEvents"
            widget: "list"
            create: true
            fields:
              - {
                  label: "Event Title",
                  name: "profEventTitle",
                  widget: "string",
                }
              - {
                  label: "Event Description ",
                  name: "profEventDescription",
                  widget: "string",
                }
              - { label: "Photo", name: "profEventImage", widget: "image" }
          - {
              label: "Calendar Link Title",
              name: "calLinkTitle",
              widget: "string",
            }
          - { label: "Calendar URL", name: "calURL", widget: "string" }
      - file: "src/pages/outreach/index.md"
        label: "Outreach Page"
        name: "outreach"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "outreach-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: "Events Section Title",
              name: sectionTitle,
              widget: string,
            }
          - {
              label: "Events Section Description",
              name: sectionDescription,
              widget: string,
            }
          - label: "Upcoming Events"
            name: "outreachEvents"
            widget: "list"
            create: true
            fields:
              - {
                  label: "Event Title",
                  name: "outreachEventTitle",
                  widget: "string",
                }
              - {
                  label: "Event Description ",
                  name: "outreachEventDescription",
                  widget: "string",
                }
              - { label: "Photo", name: "outreachEventImage", widget: "image" }
          - {
              label: "Calendar Link Title",
              name: "calLinkTitle",
              widget: "string",
            }
          - { label: "Calendar URL", name: "calURL", widget: "string" }
      - file: "src/pages/contact/index.md"
        label: "contact Page"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - { label: Section Title, name: title, widget: string }
          - { label: Submit Link, name: submitLink, widget: string}
